// Vince Petrelli All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGamePlayTags
{
	/*input Tags*/
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);


	/*Player Tag  */

	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);

	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);


	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ABD_RPGGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);

}
